/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package igu;

import logica.logicaMedidas;

/**
 *
 * @author cristian
 */
public class Medidas extends javax.swing.JPanel {

    /**
     * Creates new form Medidas
     */
    public Medidas() {
        initComponents();
    }

    logicaMedidas med = new logicaMedidas();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtMedida = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboA1 = new javax.swing.JComboBox<>();
        cboDe1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lResultado = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnConvertir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMedida.setBackground(new java.awt.Color(255, 255, 255));
        txtMedida.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        txtMedida.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 150, 40));

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RESULTADO ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, -1, -1));

        cboA1.setBackground(new java.awt.Color(255, 255, 255));
        cboA1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        cboA1.setForeground(new java.awt.Color(0, 0, 0));
        cboA1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centimetro", "Metro", "Kilometro", "Milla", "Yarda", "Pie", "Milla Nautica" }));
        jPanel1.add(cboA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        cboDe1.setBackground(new java.awt.Color(255, 255, 255));
        cboDe1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        cboDe1.setForeground(new java.awt.Color(0, 0, 0));
        cboDe1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centimetro", "Metro", "Kilometro", "Milla", "yarda", "Pie", "Milla Nautica" }));
        jPanel1.add(cboDe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONVERTIR A");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INGRESE UNA MEDIDA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        lResultado.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        lResultado.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 100, 60));

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CONVERTIR DE ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        btnConvertir.setBackground(new java.awt.Color(0, 0, 0));
        btnConvertir.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        btnConvertir.setForeground(new java.awt.Color(51, 102, 255));
        btnConvertir.setText("CONVERTIR");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });
        jPanel1.add(btnConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 170, -1));

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(51, 102, 255));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 170, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 204), new java.awt.Color(0, 51, 204), new java.awt.Color(0, 51, 204), new java.awt.Color(0, 51, 204)));

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONVERSOR DE MEDIDAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 720, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        med.medidas();
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       txtMedida.setText("");
       lResultado.setText("");
       cboDe1.setSelectedIndex(0);
       cboA1.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JButton btnLimpiar;
    public static javax.swing.JComboBox<String> cboA1;
    public static javax.swing.JComboBox<String> cboDe1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lResultado;
    public static javax.swing.JTextField txtMedida;
    // End of variables declaration//GEN-END:variables
}
