/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import java.awt.BorderLayout;

/**
 *
 * @author cristian
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        PortadaInicio p0 = new PortadaInicio();
        p0.setSize(800, 500);
        p0.setLocation(0, 0);
        
        contenedor.removeAll();
        contenedor.add(p0,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDivisas = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnMedidas = new javax.swing.JButton();
        contenedor = new javax.swing.JPanel();
        btnTemperaturas = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("CONVERSORES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        btnDivisas.setBackground(new java.awt.Color(0, 0, 0));
        btnDivisas.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        btnDivisas.setForeground(new java.awt.Color(51, 153, 255));
        btnDivisas.setText("CONVERSOR DIVISAS");
        btnDivisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisasActionPerformed(evt);
            }
        });
        jPanel1.add(btnDivisas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 230, 40));

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(153, 0, 51));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, 190, 40));

        btnMedidas.setBackground(new java.awt.Color(0, 0, 0));
        btnMedidas.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        btnMedidas.setForeground(new java.awt.Color(51, 153, 255));
        btnMedidas.setText("CONVERSOR MEDIDAS");
        btnMedidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedidasActionPerformed(evt);
            }
        });
        jPanel1.add(btnMedidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 230, 40));

        contenedor.setBackground(new java.awt.Color(153, 153, 153));
        contenedor.setPreferredSize(new java.awt.Dimension(850, 650));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 800, 500));

        btnTemperaturas.setBackground(new java.awt.Color(0, 0, 0));
        btnTemperaturas.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        btnTemperaturas.setForeground(new java.awt.Color(51, 153, 255));
        btnTemperaturas.setText("CONV TEMPERATURAS");
        btnTemperaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemperaturasActionPerformed(evt);
            }
        });
        jPanel1.add(btnTemperaturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 235, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMedidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedidasActionPerformed
       Medidas p2 = new Medidas();
        p2.setSize(800, 500);
        p2.setLocation(0, 0);
        
        contenedor.removeAll();
        contenedor.add(p2,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnMedidasActionPerformed

    private void btnDivisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisasActionPerformed
      Divisas p1 = new Divisas();
        p1.setSize(800, 500);
        p1.setLocation(0, 0);
        
        contenedor.removeAll();
        contenedor.add(p1,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
        
    }//GEN-LAST:event_btnDivisasActionPerformed

    private void btnTemperaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemperaturasActionPerformed
       Temperaturas p3 = new Temperaturas();
        p3.setSize(800, 500);
        p3.setLocation(0, 0);
        
        contenedor.removeAll();
        contenedor.add(p3,BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_btnTemperaturasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDivisas;
    private javax.swing.JButton btnMedidas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTemperaturas;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
